#!/bin/sh /etc/rc.common
# Copyright 2025 Rafał Wabik (IceG) - From eko.one.pl forum
# This version modded by iamromulan from GitHub
# Licensed to the GNU General Public License v3.0.

USE_PROCD=1
START=99
STOP=01

start() {
    mkdir -p /tmp/qfirehoseupload
    chmod 777 /tmp/qfirehoseupload
    chown nobody:nogroup /tmp/qfirehoseupload


    mkdir -p /var/log/qfirehose
    chmod 777 /var/log/qfirehose
    chown nobody:nogroup /var/log/qfirehose


    chmod 755 /usr/sbin/qfirehose-start
    chmod 755 /usr/sbin/qfirehose-status
    chown nobody:nogroup /usr/sbin/qfirehose-start
    chown nobody:nogroup /usr/sbin/qfirehose-status

    touch /tmp/qfirehose_debug.log
    chmod 666 /tmp/qfirehose_debug.log
    chown nobody:nogroup /tmp/qfirehose_debug.log
}


stop() {
    :
}
