#!/bin/sh


if [ ! -f "/tmp/qfirehose_log/pid" ]; then
    echo "Process not found"
    exit 1
fi


PID=$(cat /tmp/qfirehose_log/pid)


if ! kill -0 $PID 2>/dev/null; then
    if [ -f "/tmp/qfirehose_log/current.log" ]; then
        tail -n 20 /tmp/qfirehose_log/current.log
        if grep -q "Firmware flashed successfully" /tmp/qfirehose_log/current.log; then
            echo "completed"
            rm -f /tmp/qfirehose_log/pid
            exit 0
        else
            echo "failed"
            rm -f /tmp/qfirehose_log/pid
            exit 1
        fi
    fi
else
    if [ -f "/tmp/qfirehose_log/current.log" ]; then
        tail -n 5 /tmp/qfirehose_log/current.log
    fi
    exit 0
fi
